### PR TITLE
Fixes requirement for ansible host to have sudo rights

### PR DESCRIPTION
**Pull request by ShyamsundarR**
Signed-off-by: ShyamsundarR <srangana@redhat.com>

### CODE REVIEW

**Comment by ShyamsundarR** [comment]
Fixes #22 

Tested against live deployment as follows,

./roles/test/tasks/main.yml
```
---
# vim: set ts=2 sw=2 et :
- name: test local actions
  become: false
  local_action: "command uname -a"
  register: testout

- name: Check output
  debug:
    msg: "Got output of: {{ testout.stdout }}"
```

./test-play.yml
```
# vim: set ts=2 sw=2 et :
---
- hosts: all
  become: false
  tasks:
  - ping:

- name: Testing role
  hosts: all
  become: true
  roles:
  - test
```

Run as: `./ansible-ec2 -l <a-group> ./test-play.yml`

Fails when `become: false` is removed from task "test local actions" and user running the playbook is not in sudoers, passes when it is reverted.

**Review by JohnStrunk — COMMENTED** [review]
I suspect the tasks "Set mode for certs" and "clean up local temp directory" also need `become: false`

**Comment by ShyamsundarR** [comment]
> I suspect the tasks "Set mode for certs" and "clean up local temp directory" also need become: false

Ack, fixed in the next commit.

**Review by JohnStrunk — APPROVED** [review]
LGTM

**Pull request merged**
